services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/model/model.joblib:/app/src/model/model.joblib
 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
