services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "${MLFLOW_PORT}:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/app/mlflow.db
    working_dir: /app
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///app/mlflow.db
      --default-artifact-root file:///mlruns
      --allowed-hosts "*"
      --cors-allowed-origins "*"
    environment:
      - MLFLOW_ALLOW_HOST=all
      - MLFLOW_HOST_WHITELIST=*

  trainer:
    build: .
    command: uv run src/model/train.py
    depends_on:
      mlflow:
        condition: service_healthy

  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    depends_on:
      trainer:
        condition: service_completed_successfully
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:8501"
    depends_on:
      - api
